-- Classic Cosmetics: run in the Supabase SQL editor. Enable RLS before production data.
create extension if not exists pgcrypto;
create table categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, created_at timestamptz not null default now());
create table brands (id uuid primary key default gen_random_uuid(), category_id uuid not null references categories(id) on delete cascade, name text not null, slug text not null, logo_url text, created_at timestamptz not null default now(), unique(category_id, slug));
create table products (id uuid primary key default gen_random_uuid(), name text not null, description text, category_id uuid references categories(id) on delete set null, brand_id uuid references brands(id) on delete set null, price numeric(10,2) not null check(price >= 0), stock integer not null default 0 check(stock >= 0), images text[] not null default '{}', status text not null default 'in_stock' check(status in ('in_stock','out_of_stock')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table orders (id uuid primary key default gen_random_uuid(), order_number text not null unique, name text not null, phone text not null, address text not null, city text not null, customer_name text not null, customer_phone text not null, customer_address text not null, items jsonb not null default '[]'::jsonb, total_amount numeric(10,2) not null check(total_amount >= 0), payment_method text not null check(payment_method in ('cod','easypaisa','jazzcash','card')), payment_status text not null default 'pending' check(payment_status in ('pending','paid','failed')), status text not null default 'Pending' check(status in ('Pending','Processing','Confirmed','Delivered','Cancelled')), order_status text not null default 'pending' check(order_status in ('pending','confirmed','processing','shipped','delivered','cancelled')), created_at timestamptz not null default now());
create table order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references orders(id) on delete cascade, product_id uuid references products(id) on delete set null, product_name text not null, quantity integer not null check(quantity > 0), unit_price numeric(10,2) not null check(unit_price >= 0));
create table admin_users (id uuid primary key references auth.users(id) on delete cascade, email text not null, created_at timestamptz not null default now());
alter table categories enable row level security; alter table brands enable row level security; alter table products enable row level security; alter table orders enable row level security; alter table order_items enable row level security; alter table admin_users enable row level security;
create or replace function is_admin() returns boolean language sql security definer stable as $$ select exists(select 1 from admin_users where id=auth.uid()) $$;
create policy "public read categories" on categories for select using (true); create policy "admin manage categories" on categories for all using (is_admin());
create policy "public read brands" on brands for select using (true); create policy "admin manage brands" on brands for all using (is_admin());
create policy "public read products" on products for select using (true); create policy "admin manage products" on products for all using (is_admin());
create policy "public create orders" on orders for insert with check (true); create policy "admin manage orders" on orders for all using (is_admin()); create policy "admin manage order items" on order_items for all using (is_admin()); create policy "admin sees self" on admin_users for select using (auth.uid()=id);
-- Use an RPC for checkout in production so prices are calculated from products server-side (see supplied backend schema).
