/* Seed list of brand names sourced from the public reference brand directory.
   Used ONCE to bootstrap the central Brands store. After that every brand is
   fully managed from the admin Brands Management page (editable + deletable). */
export const referenceBrandNames = [
  "4me", "Abib", "Acca Kappa", "Accufix",
  "Adidas", "Admiral", "Afnan", "Aichun",
  "Ajmal", "Always", "Always - P&G", "Anastasia Beverly Hills",
  "Andalou", "Antonio Banderas", "Anua", "AQ Cosmetics",
  "Arencia", "Ariul", "ARTDECO", "AVEENO",
  "Axe", "Axis-Y", "AZTEC SECRET", "Azzaro",
  "B&B Derma", "Babi Mild", "Banana Boat", "BANILA CO",
  "Bath & Body Works", "Batiste", "BBA Cosmetics", "Beautenic",
  "Beauty Formulas", "Beauty of Joseon", "Benefit", "Benetton",
  "Beurer", "BIC", "Bigen", "bioaqua",
  "Biodance", "Bioderma", "bleuface", "Bloom Effekt",
  "Bob", "Body Luxuries", "Bold", "Bourjois",
  "Broche", "Brut", "Burberry", "Butterfly",
  "Byoma", "Callista Beauty", "Calvin Klein", "Cappuvini",
  "Capri", "Carefree", "Carex", "Carla Secret",
  "Celimax", "Centellian24", "Cerave DBD", "Cetaphil",
  "Charlotte Tilbury", "CHI", "Chirs's", "Christine",
  "Clean & Clear", "Clear", "Clear- Unilever Pakistan", "Clinique",
  "clio", "Colgate", "Color Studio", "Color Wow",
  "Conatural", "Cosmo", "COSRX", "Coty Airspun",
  "Creation Lamis", "Cussons Creations", "d'Alba", "Dari Mooch",
  "DAVID BEKHAM", "Davidoff", "Denim", "Depilia",
  "Derma shine", "Dexe", "Dial", "Dior",
  "Disaar", "Disunie", "Dove", "Dove- Unilever Pakistan",
  "Dr Althea", "DR RASHEL", "Dr. Althea", "Dragon Ranee",
  "Dsquared2", "Dunhill", "Durex", "Durex Pakistan",
  "ELF", "ELIZABETH ARDEN", "Elizabeth Taylor", "ELLIPS",
  "Elmore", "Embryolisse", "Emeron", "Enchanteur",
  "Endurance", "Enliven", "Eos", "Eqqual Berry",
  "Essence", "ESTELIN", "ETUDE", "Eveline",
  "Fa", "Fabbrica Della Musa", "Facial Beauty", "Fascino",
  "Fay", "Fayankou", "Feather Flamingos", "Feel",
  "Fenty Beauty", "Flormar", "Framesi", "Fruton",
  "Fun Time", "Fused", "Fute", "FW Organics",
  "Gabrini", "Garnier", "Garnier HairCare", "Garnier SkinCare",
  "Gatsby", "Gege Bear", "Gegemoon", "Gilette",
  "Gillette", "Gillette - P&G", "Giorgio Armani", "Glamorous Face",
  "Glossier", "Glow & Lovely- Unilever Pakistan", "Glow Beauty", "Glow Recipe",
  "Glysolid", "Gosh", "Got2B", "GrandeFanatic",
  "Guanjing", "Gucci", "Hair Pantry", "HANDAIYAN",
  "HaruHaru", "Haya Beauty", "Head & Shoulders - P&G", "Heimish",
  "Hemani Herbals", "Heng Fang", "Herbal Essences", "HerBeauty",
  "Herbion", "Herorange", "Highfy", "Highfy gifts",
  "Highfy.pk", "Himalaya", "HUDA BEAUTY", "HUGO BOSS",
  "HYPE", "I'm From", "IGB", "IKT",
  "Images", "Imperial Leather", "Impulse", "Initial",
  "Invictus", "Irish Spring", "Isntree", "J.",
  "J. Note", "J. Skincare", "Jaguar", "Janssen",
  "JAWA", "Jean Paul Gaultier", "jenpharm", "Jergens",
  "JIMMY CHOO", "John Allen", "John Frieda", "Johnsons",
  "Josh", "Jovan", "Jugnu Candle", "Jumiso",
  "Just Awesome", "Just For Men", "K-Secret", "Karseell",
  "Kemei", "Kemei Pakistan", "Kenneth Cole", "Kevin & Coco",
  "Klean Beauty", "Kodomo", "Kohasaa", "Kotex",
  "Kris", "Krone", "Kryolan", "KY",
  "L'Oreal Deodorant", "L'Oreal Haircare", "L'Oreal Makeup", "L'Oreal Personal Care",
  "L'Oreal Professional", "L'Oreal Skincare", "L'Oreal USA", "L.A GIRL",
  "LA Roche Posay", "Labello", "Lady Speed", "Lalique",
  "Lamel", "Lancaster", "LANEIGE", "Lattafa",
  "Legacy", "Lifebuoy- Unilever Pakistan", "Lilyeve", "Listerine",
  "Lolita Lempicka", "Lorenay", "Lurella", "Lux",
  "Lux- Unilever Pakistan", "MAC", "Mak's", "Makeup Revolution",
  "Mary&May", "Masarrat Misbah", "Maui", "MAX FACTOR",
  "Maybelline", "Maybelline USA", "Meclay London", "Medicube",
  "Medora", "MERCEDEZ", "Mielle", "Milk Makeup",
  "Miss Lara", "miss rose", "Mixsoon", "Mom's Bath Recipe",
  "MORPHE", "Moschino", "Mothercare Pakistan", "MUA",
  "Muicin", "Nabila Haircare", "nars", "Nautica",
  "Neophar Skin Sciences", "Neutrogena", "Nexton", "Nineless",
  "Nirvana Botanics", "Nishman", "Nivea", "Noubablak",
  "Numbuzin", "Nyx", "OGX", "Oilatum",
  "OK", "Olay", "Old Spice", "Olivia",
  "One Size", "Oneskin", "OneSpring", "onestep",
  "Oral B", "Organic Traveller", "Paco Rabanne", "Palmer's",
  "Palmolive", "PanOxyl", "Pantene", "Pantene - P&G",
  "Paris Hilton", "Parwaz", "Paula choice", "Pepe Jeans",
  "Philips", "Physiogel", "Pierre Cardin Paris", "PinkFlash",
  "Pixi", "Ponds", "Ponds- Unilever Pakistan", "Posch",
  "Potion", "Pretty Cosmetic", "Prince Matchabelli", "Pupa Milano",
  "Pur", "Purito", "Quest", "Radox",
  "Rare Beauty", "RASASI", "REAL TECHNIQUE", "Rederm",
  "REMINGTON", "Revlon", "Revlon Professional", "Rexona",
  "Rhode", "RICA", "Rimmel", "Rind",
  "Rivaj", "Rough Rider", "Round Lab", "Rude Cosmetics",
  "Rue Broca", "Sabalon", "Sadoer", "Saeed Ghani",
  "saie", "Sally Hansen", "SANIDERM", "Savannah",
  "Scents N Secrets", "Scents N Stories", "Schwarzkopf", "SEBAMED",
  "Secret Key", "Sheglam", "Shein", "Shiseido",
  "Silky Cool", "Simple", "SJP", "Skin Deep",
  "Skin Pantry", "SKIN1004", "Skinjoy", "Skinly",
  "Soap & Glory", "Sol de Janeiro", "Some By Mi", "Spirit Of Kings",
  "ST London", "St. Ives", "Stilla", "Stives",
  "Suave", "Sudocrem", "SUNKISSED", "Sunsilk",
  "Sunsilk- Unilever Pakistan", "SURE", "Swabe", "Swansi",
  "Sweetface", "Swiss Miss", "Tampax", "Tarte",
  "TFIT", "The Face Shop", "The Purest Solution", "Tio Nacho",
  "Tirtir", "Tocobo", "Tommy Bahama", "Tommy Hilfiger",
  "Too Faced", "Tresemme", "Tresemme- Unilever Pakistan", "Trouble Maker Cosmetics",
  "Truly Komal", "Tune", "Vaseline", "Vaseline - Unilever Pakistan",
  "Vatika", "Veet", "Veet Pakistan", "Versace",
  "Verve House", "Veze", "VI'DA", "Victoria's Secret",
  "Vince", "VLCC", "VT", "Wella",
  "Westpoint", "WET N WILD", "Wilkinson", "Wokali",
  "Women secret", "XHC", "Xpel", "Yardley",
  "Yves Saint Laurent", "Zeena", "Zero Makeup", "Zinc",
  "Zonanos",
];
